// Auto-generated periodic table data (118 elements)
const ELEMENTS = [
  {
    "number": 1,
    "symbol": "H",
    "name": "Hydrogen",
    "mass": "1.008",
    "category": "nonmetal",
    "period": 1,
    "group": 1,
    "phase": "gas",
    "discovered": "1766",
    "fact": "It's the lightest and most common element in the whole universe!",
    "use": "Powers the Sun and stars through fusion."
  },
  {
    "number": 2,
    "symbol": "He",
    "name": "Helium",
    "mass": "4.003",
    "category": "noble-gas",
    "period": 1,
    "group": 18,
    "phase": "gas",
    "discovered": "1868",
    "fact": "It makes your voice squeaky and helium balloons float!",
    "use": "Fills party balloons and blimps."
  },
  {
    "number": 3,
    "symbol": "Li",
    "name": "Lithium",
    "mass": "6.94",
    "category": "alkali-metal",
    "period": 2,
    "group": 1,
    "phase": "solid",
    "discovered": "1817",
    "fact": "It's so light it can float on water, and it's super reactive!",
    "use": "Used in rechargeable batteries for phones."
  },
  {
    "number": 4,
    "symbol": "Be",
    "name": "Beryllium",
    "mass": "9.012",
    "category": "alkaline-earth",
    "period": 2,
    "group": 2,
    "phase": "solid",
    "discovered": "1798",
    "fact": "It's a strong, lightweight metal used in space equipment!",
    "use": "Used in aircraft and satellite parts."
  },
  {
    "number": 5,
    "symbol": "B",
    "name": "Boron",
    "mass": "10.81",
    "category": "metalloid",
    "period": 2,
    "group": 13,
    "phase": "solid",
    "discovered": "1808",
    "fact": "It makes glass super tough so it won't crack from heat!",
    "use": "Used to make heat-resistant glass, like Pyrex."
  },
  {
    "number": 6,
    "symbol": "C",
    "name": "Carbon",
    "mass": "12.011",
    "category": "nonmetal",
    "period": 2,
    "group": 14,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "It's the building block of all living things, including you!",
    "use": "Forms diamonds, pencils, and every living cell."
  },
  {
    "number": 7,
    "symbol": "N",
    "name": "Nitrogen",
    "mass": "14.007",
    "category": "nonmetal",
    "period": 2,
    "group": 15,
    "phase": "gas",
    "discovered": "1772",
    "fact": "It makes up about 78% of the air you're breathing right now!",
    "use": "Used to make fertilizer that helps plants grow."
  },
  {
    "number": 8,
    "symbol": "O",
    "name": "Oxygen",
    "mass": "15.999",
    "category": "nonmetal",
    "period": 2,
    "group": 16,
    "phase": "gas",
    "discovered": "1774",
    "fact": "You need it every second to breathe and stay alive!",
    "use": "Essential for breathing and burning fires."
  },
  {
    "number": 9,
    "symbol": "F",
    "name": "Fluorine",
    "mass": "18.998",
    "category": "halogen",
    "period": 2,
    "group": 17,
    "phase": "gas",
    "discovered": "1886",
    "fact": "It's the most reactive element and keeps your teeth strong!",
    "use": "Added to toothpaste to fight cavities."
  },
  {
    "number": 10,
    "symbol": "Ne",
    "name": "Neon",
    "mass": "20.180",
    "category": "noble-gas",
    "period": 2,
    "group": 18,
    "phase": "gas",
    "discovered": "1898",
    "fact": "It glows bright orange-red inside glass signs!",
    "use": "Lights up colorful neon signs."
  },
  {
    "number": 11,
    "symbol": "Na",
    "name": "Sodium",
    "mass": "22.990",
    "category": "alkali-metal",
    "period": 3,
    "group": 1,
    "phase": "solid",
    "discovered": "1807",
    "fact": "Mixed with chlorine, it becomes the salt on your fries!",
    "use": "Combines with chlorine to make table salt."
  },
  {
    "number": 12,
    "symbol": "Mg",
    "name": "Magnesium",
    "mass": "24.305",
    "category": "alkaline-earth",
    "period": 3,
    "group": 2,
    "phase": "solid",
    "discovered": "1808",
    "fact": "It burns with a dazzling bright white light!",
    "use": "Used in fireworks and lightweight bike frames."
  },
  {
    "number": 13,
    "symbol": "Al",
    "name": "Aluminum",
    "mass": "26.982",
    "category": "post-transition-metal",
    "period": 3,
    "group": 13,
    "phase": "solid",
    "discovered": "1825",
    "fact": "It's light, doesn't rust, and can be recycled forever!",
    "use": "Used to make soda cans and foil."
  },
  {
    "number": 14,
    "symbol": "Si",
    "name": "Silicon",
    "mass": "28.085",
    "category": "metalloid",
    "period": 3,
    "group": 14,
    "phase": "solid",
    "discovered": "1824",
    "fact": "It's the main ingredient in sand and computer chips!",
    "use": "Used to build computer chips and glass."
  },
  {
    "number": 15,
    "symbol": "P",
    "name": "Phosphorus",
    "mass": "30.974",
    "category": "nonmetal",
    "period": 3,
    "group": 15,
    "phase": "solid",
    "discovered": "1669",
    "fact": "It can glow in the dark, which is how it got its name!",
    "use": "Found in matches and your own bones."
  },
  {
    "number": 16,
    "symbol": "S",
    "name": "Sulfur",
    "mass": "32.06",
    "category": "nonmetal",
    "period": 3,
    "group": 16,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "It smells like rotten eggs when it reacts with things!",
    "use": "Used to make rubber and matches."
  },
  {
    "number": 17,
    "symbol": "Cl",
    "name": "Chlorine",
    "mass": "35.45",
    "category": "halogen",
    "period": 3,
    "group": 17,
    "phase": "gas",
    "discovered": "1774",
    "fact": "It keeps swimming pools clean and free of germs!",
    "use": "Disinfects drinking water and pools."
  },
  {
    "number": 18,
    "symbol": "Ar",
    "name": "Argon",
    "mass": "39.948",
    "category": "noble-gas",
    "period": 3,
    "group": 18,
    "phase": "gas",
    "discovered": "1894",
    "fact": "It fills light bulbs so the glowing metal inside doesn't burn up!",
    "use": "Fills light bulbs to make them last longer."
  },
  {
    "number": 19,
    "symbol": "K",
    "name": "Potassium",
    "mass": "39.098",
    "category": "alkali-metal",
    "period": 4,
    "group": 1,
    "phase": "solid",
    "discovered": "1807",
    "fact": "Bananas are famous for having lots of it!",
    "use": "Helps your muscles and nerves work properly."
  },
  {
    "number": 20,
    "symbol": "Ca",
    "name": "Calcium",
    "mass": "40.078",
    "category": "alkaline-earth",
    "period": 4,
    "group": 2,
    "phase": "solid",
    "discovered": "1808",
    "fact": "It's what makes your bones and teeth super strong!",
    "use": "Builds strong bones and teeth."
  },
  {
    "number": 21,
    "symbol": "Sc",
    "name": "Scandium",
    "mass": "44.956",
    "category": "transition-metal",
    "period": 4,
    "group": 3,
    "phase": "solid",
    "discovered": "1879",
    "fact": "It's mixed with aluminum to make super light baseball bats!",
    "use": "Used in lightweight sports equipment."
  },
  {
    "number": 22,
    "symbol": "Ti",
    "name": "Titanium",
    "mass": "47.867",
    "category": "transition-metal",
    "period": 4,
    "group": 4,
    "phase": "solid",
    "discovered": "1791",
    "fact": "It's as strong as steel but way lighter, and it's in spaceships!",
    "use": "Used in jet engines and artificial hips."
  },
  {
    "number": 23,
    "symbol": "V",
    "name": "Vanadium",
    "mass": "50.942",
    "category": "transition-metal",
    "period": 4,
    "group": 5,
    "phase": "solid",
    "discovered": "1801",
    "fact": "It makes steel tools stronger and more shock-resistant!",
    "use": "Strengthens steel for tools and springs."
  },
  {
    "number": 24,
    "symbol": "Cr",
    "name": "Chromium",
    "mass": "51.996",
    "category": "transition-metal",
    "period": 4,
    "group": 6,
    "phase": "solid",
    "discovered": "1797",
    "fact": "It gives shiny chrome bumpers their mirror-like sparkle!",
    "use": "Coats metal to make it shiny and rust-proof."
  },
  {
    "number": 25,
    "symbol": "Mn",
    "name": "Manganese",
    "mass": "54.938",
    "category": "transition-metal",
    "period": 4,
    "group": 7,
    "phase": "solid",
    "discovered": "1774",
    "fact": "Almost all steel in the world contains a bit of it!",
    "use": "Strengthens steel and is found in batteries."
  },
  {
    "number": 26,
    "symbol": "Fe",
    "name": "Iron",
    "mass": "55.845",
    "category": "transition-metal",
    "period": 4,
    "group": 8,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "It's inside your blood, carrying oxygen all over your body!",
    "use": "Makes steel and travels in your red blood cells."
  },
  {
    "number": 27,
    "symbol": "Co",
    "name": "Cobalt",
    "mass": "58.933",
    "category": "transition-metal",
    "period": 4,
    "group": 9,
    "phase": "solid",
    "discovered": "1735",
    "fact": "It gives glass and paint a brilliant deep blue color!",
    "use": "Colors glass blue and powers rechargeable batteries."
  },
  {
    "number": 28,
    "symbol": "Ni",
    "name": "Nickel",
    "mass": "58.693",
    "category": "transition-metal",
    "period": 4,
    "group": 10,
    "phase": "solid",
    "discovered": "1751",
    "fact": "American 5-cent coins are named after it!",
    "use": "Used to make coins and stainless steel."
  },
  {
    "number": 29,
    "symbol": "Cu",
    "name": "Copper",
    "mass": "63.546",
    "category": "transition-metal",
    "period": 4,
    "group": 11,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "It's a shiny orange metal that carries electricity super well!",
    "use": "Used in electrical wires and pennies."
  },
  {
    "number": 30,
    "symbol": "Zn",
    "name": "Zinc",
    "mass": "65.38",
    "category": "transition-metal",
    "period": 4,
    "group": 12,
    "phase": "solid",
    "discovered": "1746",
    "fact": "It's coated onto steel to stop it from rusting!",
    "use": "Protects metal from rust and helps wounds heal."
  },
  {
    "number": 31,
    "symbol": "Ga",
    "name": "Gallium",
    "mass": "69.723",
    "category": "post-transition-metal",
    "period": 4,
    "group": 13,
    "phase": "solid",
    "discovered": "1875",
    "fact": "It's a metal that can melt right in your hand!",
    "use": "Used in LED lights and smartphone screens."
  },
  {
    "number": 32,
    "symbol": "Ge",
    "name": "Germanium",
    "mass": "72.630",
    "category": "metalloid",
    "period": 4,
    "group": 14,
    "phase": "solid",
    "discovered": "1886",
    "fact": "It helps transmit signals through fiber-optic cables!",
    "use": "Used in fiber-optic internet cables."
  },
  {
    "number": 33,
    "symbol": "As",
    "name": "Arsenic",
    "mass": "74.922",
    "category": "metalloid",
    "period": 4,
    "group": 15,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "It's mostly known for being toxic, but it's also used in tiny electronics!",
    "use": "Used in small amounts in semiconductors."
  },
  {
    "number": 34,
    "symbol": "Se",
    "name": "Selenium",
    "mass": "78.971",
    "category": "nonmetal",
    "period": 4,
    "group": 16,
    "phase": "solid",
    "discovered": "1817",
    "fact": "It can turn light directly into electricity!",
    "use": "Used in solar panels and photocopiers."
  },
  {
    "number": 35,
    "symbol": "Br",
    "name": "Bromine",
    "mass": "79.904",
    "category": "halogen",
    "period": 4,
    "group": 17,
    "phase": "liquid",
    "discovered": "1826",
    "fact": "It's one of only two elements that are liquid at room temperature!",
    "use": "Used in flame-resistant materials."
  },
  {
    "number": 36,
    "symbol": "Kr",
    "name": "Krypton",
    "mass": "83.798",
    "category": "noble-gas",
    "period": 4,
    "group": 18,
    "phase": "gas",
    "discovered": "1898",
    "fact": "Superman's home planet was named after this real element!",
    "use": "Used in bright, energy-saving lights."
  },
  {
    "number": 37,
    "symbol": "Rb",
    "name": "Rubidium",
    "mass": "85.468",
    "category": "alkali-metal",
    "period": 5,
    "group": 1,
    "phase": "solid",
    "discovered": "1861",
    "fact": "It bursts into flame the instant it touches air!",
    "use": "Used in precise atomic clocks."
  },
  {
    "number": 38,
    "symbol": "Sr",
    "name": "Strontium",
    "mass": "87.62",
    "category": "alkaline-earth",
    "period": 5,
    "group": 2,
    "phase": "solid",
    "discovered": "1790",
    "fact": "It burns bright red, lighting up fireworks shows!",
    "use": "Colors fireworks a brilliant red."
  },
  {
    "number": 39,
    "symbol": "Y",
    "name": "Yttrium",
    "mass": "88.906",
    "category": "transition-metal",
    "period": 5,
    "group": 3,
    "phase": "solid",
    "discovered": "1794",
    "fact": "It helps make the red color in old TV screens!",
    "use": "Used in LED lights and camera lenses."
  },
  {
    "number": 40,
    "symbol": "Zr",
    "name": "Zirconium",
    "mass": "91.224",
    "category": "transition-metal",
    "period": 5,
    "group": 4,
    "phase": "solid",
    "discovered": "1789",
    "fact": "Sparkly cubic zirconia gems are made from it!",
    "use": "Used in fake diamonds and nuclear reactors."
  },
  {
    "number": 41,
    "symbol": "Nb",
    "name": "Niobium",
    "mass": "92.906",
    "category": "transition-metal",
    "period": 5,
    "group": 5,
    "phase": "solid",
    "discovered": "1801",
    "fact": "It's used in super-strong magnets for MRI machines!",
    "use": "Used in medical MRI scanner magnets."
  },
  {
    "number": 42,
    "symbol": "Mo",
    "name": "Molybdenum",
    "mass": "95.95",
    "category": "transition-metal",
    "period": 5,
    "group": 6,
    "phase": "solid",
    "discovered": "1781",
    "fact": "It helps make some of the strongest steel alloys on Earth!",
    "use": "Strengthens steel used in tools and pipelines."
  },
  {
    "number": 43,
    "symbol": "Tc",
    "name": "Technetium",
    "mass": "(98)",
    "category": "transition-metal",
    "period": 5,
    "group": 7,
    "phase": "solid",
    "discovered": "1937",
    "fact": "It was the first element ever made by humans instead of found in nature!",
    "use": "Used to help doctors take medical scans."
  },
  {
    "number": 44,
    "symbol": "Ru",
    "name": "Ruthenium",
    "mass": "101.07",
    "category": "transition-metal",
    "period": 5,
    "group": 8,
    "phase": "solid",
    "discovered": "1844",
    "fact": "It's added to platinum jewelry to make it extra hard!",
    "use": "Hardens platinum and palladium for jewelry."
  },
  {
    "number": 45,
    "symbol": "Rh",
    "name": "Rhodium",
    "mass": "102.906",
    "category": "transition-metal",
    "period": 5,
    "group": 9,
    "phase": "solid",
    "discovered": "1803",
    "fact": "It's one of the rarest and shiniest metals on Earth!",
    "use": "Coats jewelry to make it extra shiny."
  },
  {
    "number": 46,
    "symbol": "Pd",
    "name": "Palladium",
    "mass": "106.42",
    "category": "transition-metal",
    "period": 5,
    "group": 10,
    "phase": "solid",
    "discovered": "1803",
    "fact": "Your family's car uses it to clean up exhaust fumes!",
    "use": "Cleans exhaust gases in car catalytic converters."
  },
  {
    "number": 47,
    "symbol": "Ag",
    "name": "Silver",
    "mass": "107.868",
    "category": "transition-metal",
    "period": 5,
    "group": 11,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "It's the best metal on Earth at conducting electricity!",
    "use": "Used in jewelry, coins, and electronics."
  },
  {
    "number": 48,
    "symbol": "Cd",
    "name": "Cadmium",
    "mass": "112.414",
    "category": "transition-metal",
    "period": 5,
    "group": 12,
    "phase": "solid",
    "discovered": "1817",
    "fact": "It used to glow in old TV screens to make colors pop!",
    "use": "Used in rechargeable nickel-cadmium batteries."
  },
  {
    "number": 49,
    "symbol": "In",
    "name": "Indium",
    "mass": "114.818",
    "category": "post-transition-metal",
    "period": 5,
    "group": 13,
    "phase": "solid",
    "discovered": "1863",
    "fact": "It makes a strange, high-pitched cry when you bend it!",
    "use": "Coats touchscreens so your finger can control them."
  },
  {
    "number": 50,
    "symbol": "Sn",
    "name": "Tin",
    "mass": "118.710",
    "category": "post-transition-metal",
    "period": 5,
    "group": 14,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "People have used it for thousands of years to coat cans!",
    "use": "Coats steel cans to stop them from rusting."
  },
  {
    "number": 51,
    "symbol": "Sb",
    "name": "Antimony",
    "mass": "121.760",
    "category": "metalloid",
    "period": 5,
    "group": 15,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "Ancient Egyptians used it as a dark eye makeup!",
    "use": "Used to make batteries and flame-proof fabric."
  },
  {
    "number": 52,
    "symbol": "Te",
    "name": "Tellurium",
    "mass": "127.60",
    "category": "metalloid",
    "period": 5,
    "group": 16,
    "phase": "solid",
    "discovered": "1782",
    "fact": "It can make people's breath smell like garlic!",
    "use": "Used in solar panels and metal alloys."
  },
  {
    "number": 53,
    "symbol": "I",
    "name": "Iodine",
    "mass": "126.904",
    "category": "halogen",
    "period": 5,
    "group": 17,
    "phase": "solid",
    "discovered": "1811",
    "fact": "Your body needs a tiny bit to keep your thyroid healthy!",
    "use": "Added to table salt to keep you healthy."
  },
  {
    "number": 54,
    "symbol": "Xe",
    "name": "Xenon",
    "mass": "131.293",
    "category": "noble-gas",
    "period": 5,
    "group": 18,
    "phase": "gas",
    "discovered": "1898",
    "fact": "It's used to power some spacecraft engines!",
    "use": "Used in bright camera flashes and car headlights."
  },
  {
    "number": 55,
    "symbol": "Cs",
    "name": "Cesium",
    "mass": "132.905",
    "category": "alkali-metal",
    "period": 6,
    "group": 1,
    "phase": "solid",
    "discovered": "1860",
    "fact": "The world's most accurate clocks are built using it!",
    "use": "Used inside super-precise atomic clocks."
  },
  {
    "number": 56,
    "symbol": "Ba",
    "name": "Barium",
    "mass": "137.327",
    "category": "alkaline-earth",
    "period": 6,
    "group": 2,
    "phase": "solid",
    "discovered": "1808",
    "fact": "It makes fireworks glow bright green!",
    "use": "Colors fireworks green and helps doctors see X-rays."
  },
  {
    "number": 57,
    "symbol": "La",
    "name": "Lanthanum",
    "mass": "138.905",
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "phase": "solid",
    "discovered": "1839",
    "fact": "It's used in the glass of camera lenses!",
    "use": "Used in camera lenses and studio lights."
  },
  {
    "number": 58,
    "symbol": "Ce",
    "name": "Cerium",
    "mass": "140.116",
    "category": "lanthanide",
    "period": 6,
    "group": 4,
    "phase": "solid",
    "discovered": "1803",
    "fact": "It makes sparks fly in lighter flints!",
    "use": "Sparks flint in cigarette lighters."
  },
  {
    "number": 59,
    "symbol": "Pr",
    "name": "Praseodymium",
    "mass": "140.908",
    "category": "lanthanide",
    "period": 6,
    "group": 5,
    "phase": "solid",
    "discovered": "1885",
    "fact": "It gives special welding goggles a yellow-green tint!",
    "use": "Colors glass and tints welding goggles."
  },
  {
    "number": 60,
    "symbol": "Nd",
    "name": "Neodymium",
    "mass": "144.242",
    "category": "lanthanide",
    "period": 6,
    "group": 6,
    "phase": "solid",
    "discovered": "1885",
    "fact": "It makes the strongest magnets in the world!",
    "use": "Powers super-strong magnets in headphones."
  },
  {
    "number": 61,
    "symbol": "Pm",
    "name": "Promethium",
    "mass": "(145)",
    "category": "lanthanide",
    "period": 6,
    "group": 7,
    "phase": "solid",
    "discovered": "1945",
    "fact": "It's one of the rare elements that barely exists in nature!",
    "use": "Used in tiny nuclear-powered batteries."
  },
  {
    "number": 62,
    "symbol": "Sm",
    "name": "Samarium",
    "mass": "150.36",
    "category": "lanthanide",
    "period": 6,
    "group": 8,
    "phase": "solid",
    "discovered": "1879",
    "fact": "It's used in powerful magnets that resist heat!",
    "use": "Used in strong magnets and headphones."
  },
  {
    "number": 63,
    "symbol": "Eu",
    "name": "Europium",
    "mass": "151.964",
    "category": "lanthanide",
    "period": 6,
    "group": 9,
    "phase": "solid",
    "discovered": "1901",
    "fact": "It glows red under the special light used on euro banknotes to stop fakes!",
    "use": "Helps prevent money from being faked."
  },
  {
    "number": 64,
    "symbol": "Gd",
    "name": "Gadolinium",
    "mass": "157.25",
    "category": "lanthanide",
    "period": 6,
    "group": 10,
    "phase": "solid",
    "discovered": "1880",
    "fact": "Doctors use it to make MRI pictures clearer!",
    "use": "Helps make clearer MRI medical scans."
  },
  {
    "number": 65,
    "symbol": "Tb",
    "name": "Terbium",
    "mass": "158.925",
    "category": "lanthanide",
    "period": 6,
    "group": 11,
    "phase": "solid",
    "discovered": "1843",
    "fact": "It glows bright green in energy-saving light bulbs!",
    "use": "Used in green light for TVs and bulbs."
  },
  {
    "number": 66,
    "symbol": "Dy",
    "name": "Dysprosium",
    "mass": "162.500",
    "category": "lanthanide",
    "period": 6,
    "group": 12,
    "phase": "solid",
    "discovered": "1886",
    "fact": "Its name means 'hard to get' in Greek!",
    "use": "Used in powerful magnets and lasers."
  },
  {
    "number": 67,
    "symbol": "Ho",
    "name": "Holmium",
    "mass": "164.930",
    "category": "lanthanide",
    "period": 6,
    "group": 13,
    "phase": "solid",
    "discovered": "1878",
    "fact": "It has the strongest magnetic pull of any element!",
    "use": "Used in medical and industrial lasers."
  },
  {
    "number": 68,
    "symbol": "Er",
    "name": "Erbium",
    "mass": "167.259",
    "category": "lanthanide",
    "period": 6,
    "group": 14,
    "phase": "solid",
    "discovered": "1843",
    "fact": "It gives glass a pretty pink color!",
    "use": "Boosts signals in fiber-optic cables."
  },
  {
    "number": 69,
    "symbol": "Tm",
    "name": "Thulium",
    "mass": "168.934",
    "category": "lanthanide",
    "period": 6,
    "group": 15,
    "phase": "solid",
    "discovered": "1879",
    "fact": "It's one of the rarest elements on Earth!",
    "use": "Used in portable X-ray machines."
  },
  {
    "number": 70,
    "symbol": "Yb",
    "name": "Ytterbium",
    "mass": "173.045",
    "category": "lanthanide",
    "period": 6,
    "group": 16,
    "phase": "solid",
    "discovered": "1878",
    "fact": "It's named after a tiny village in Sweden!",
    "use": "Used in super-accurate atomic clocks."
  },
  {
    "number": 71,
    "symbol": "Lu",
    "name": "Lutetium",
    "mass": "174.967",
    "category": "lanthanide",
    "period": 6,
    "group": 17,
    "phase": "solid",
    "discovered": "1907",
    "fact": "It's used to help detect cancer in hospital scanners!",
    "use": "Used in PET scan medical imaging."
  },
  {
    "number": 72,
    "symbol": "Hf",
    "name": "Hafnium",
    "mass": "178.49",
    "category": "transition-metal",
    "period": 6,
    "group": 4,
    "phase": "solid",
    "discovered": "1923",
    "fact": "It's used in the control rods of nuclear reactors!",
    "use": "Controls nuclear reactions in power plants."
  },
  {
    "number": 73,
    "symbol": "Ta",
    "name": "Tantalum",
    "mass": "180.948",
    "category": "transition-metal",
    "period": 6,
    "group": 5,
    "phase": "solid",
    "discovered": "1802",
    "fact": "Almost every cell phone has this element inside it!",
    "use": "Stores electricity inside phone capacitors."
  },
  {
    "number": 74,
    "symbol": "W",
    "name": "Tungsten",
    "mass": "183.84",
    "category": "transition-metal",
    "period": 6,
    "group": 6,
    "phase": "solid",
    "discovered": "1783",
    "fact": "It has the highest melting point of any metal!",
    "use": "Glows inside old-style light bulb filaments."
  },
  {
    "number": 75,
    "symbol": "Re",
    "name": "Rhenium",
    "mass": "186.207",
    "category": "transition-metal",
    "period": 6,
    "group": 7,
    "phase": "solid",
    "discovered": "1925",
    "fact": "It was one of the last stable elements ever discovered!",
    "use": "Used in jet engine parts."
  },
  {
    "number": 76,
    "symbol": "Os",
    "name": "Osmium",
    "mass": "190.23",
    "category": "transition-metal",
    "period": 6,
    "group": 8,
    "phase": "solid",
    "discovered": "1803",
    "fact": "It's the densest natural element on the whole planet!",
    "use": "Tips fountain pens and electrical contacts."
  },
  {
    "number": 77,
    "symbol": "Ir",
    "name": "Iridium",
    "mass": "192.217",
    "category": "transition-metal",
    "period": 6,
    "group": 9,
    "phase": "solid",
    "discovered": "1803",
    "fact": "A huge amount of it was found in rock linked to the dinosaur extinction!",
    "use": "Tips spark plugs and durable pen nibs."
  },
  {
    "number": 78,
    "symbol": "Pt",
    "name": "Platinum",
    "mass": "195.084",
    "category": "transition-metal",
    "period": 6,
    "group": 10,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "It's rarer than gold and used in fancy jewelry!",
    "use": "Used in jewelry and car exhaust systems."
  },
  {
    "number": 79,
    "symbol": "Au",
    "name": "Gold",
    "mass": "196.967",
    "category": "transition-metal",
    "period": 6,
    "group": 11,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "It never rusts or tarnishes, even after thousands of years!",
    "use": "Used in jewelry, coins, and electronics."
  },
  {
    "number": 80,
    "symbol": "Hg",
    "name": "Mercury",
    "mass": "200.592",
    "category": "transition-metal",
    "period": 6,
    "group": 12,
    "phase": "liquid",
    "discovered": "Ancient",
    "fact": "It's the only metal that's liquid at room temperature!",
    "use": "Used in old thermometers and switches."
  },
  {
    "number": 81,
    "symbol": "Tl",
    "name": "Thallium",
    "mass": "204.38",
    "category": "post-transition-metal",
    "period": 6,
    "group": 13,
    "phase": "solid",
    "discovered": "1861",
    "fact": "It used to be nicknamed the 'poisoner's poison'!",
    "use": "Used in specialized electronics and glass."
  },
  {
    "number": 82,
    "symbol": "Pb",
    "name": "Lead",
    "mass": "207.2",
    "category": "post-transition-metal",
    "period": 6,
    "group": 14,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "Ancient Romans used it to make water pipes!",
    "use": "Used in batteries and radiation shields."
  },
  {
    "number": 83,
    "symbol": "Bi",
    "name": "Bismuth",
    "mass": "208.980",
    "category": "post-transition-metal",
    "period": 6,
    "group": 15,
    "phase": "solid",
    "discovered": "Ancient",
    "fact": "It grows into stunning rainbow-colored crystals!",
    "use": "Used in stomach medicine and rainbow crystals."
  },
  {
    "number": 84,
    "symbol": "Po",
    "name": "Polonium",
    "mass": "(209)",
    "category": "metalloid",
    "period": 6,
    "group": 16,
    "phase": "solid",
    "discovered": "1898",
    "fact": "It was discovered by scientist Marie Curie!",
    "use": "Used in tools that remove static electricity."
  },
  {
    "number": 85,
    "symbol": "At",
    "name": "Astatine",
    "mass": "(210)",
    "category": "halogen",
    "period": 6,
    "group": 17,
    "phase": "solid",
    "discovered": "1940",
    "fact": "It's so rare that only a tiny amount exists on Earth at any time!",
    "use": "Studied by scientists for cancer research."
  },
  {
    "number": 86,
    "symbol": "Rn",
    "name": "Radon",
    "mass": "(222)",
    "category": "noble-gas",
    "period": 6,
    "group": 18,
    "phase": "gas",
    "discovered": "1900",
    "fact": "It's an invisible gas that can seep up from the ground!",
    "use": "Monitored in homes to keep families safe."
  },
  {
    "number": 87,
    "symbol": "Fr",
    "name": "Francium",
    "mass": "(223)",
    "category": "alkali-metal",
    "period": 7,
    "group": 1,
    "phase": "solid",
    "discovered": "1939",
    "fact": "It's so rare, only a tiny bit exists on Earth at once!",
    "use": "Studied by scientists, but too rare to use."
  },
  {
    "number": 88,
    "symbol": "Ra",
    "name": "Radium",
    "mass": "(226)",
    "category": "alkaline-earth",
    "period": 7,
    "group": 2,
    "phase": "solid",
    "discovered": "1898",
    "fact": "It used to glow in the dark on old watch dials!",
    "use": "Was once used to make glow-in-the-dark paint."
  },
  {
    "number": 89,
    "symbol": "Ac",
    "name": "Actinium",
    "mass": "(227)",
    "category": "actinide",
    "period": 7,
    "group": 3,
    "phase": "solid",
    "discovered": "1899",
    "fact": "It glows a soft blue in the dark!",
    "use": "Studied for use in cancer treatment."
  },
  {
    "number": 90,
    "symbol": "Th",
    "name": "Thorium",
    "mass": "232.038",
    "category": "actinide",
    "period": 7,
    "group": 4,
    "phase": "solid",
    "discovered": "1829",
    "fact": "Scientists think it could power future clean energy plants!",
    "use": "Being studied as a future nuclear fuel."
  },
  {
    "number": 91,
    "symbol": "Pa",
    "name": "Protactinium",
    "mass": "231.036",
    "category": "actinide",
    "period": 7,
    "group": 5,
    "phase": "solid",
    "discovered": "1913",
    "fact": "It's extremely rare and radioactive!",
    "use": "Used mainly for scientific research."
  },
  {
    "number": 92,
    "symbol": "U",
    "name": "Uranium",
    "mass": "238.029",
    "category": "actinide",
    "period": 7,
    "group": 6,
    "phase": "solid",
    "discovered": "1789",
    "fact": "It powers nuclear power plants that light up cities!",
    "use": "Fuels nuclear power plants."
  },
  {
    "number": 93,
    "symbol": "Np",
    "name": "Neptunium",
    "mass": "(237)",
    "category": "actinide",
    "period": 7,
    "group": 7,
    "phase": "solid",
    "discovered": "1940",
    "fact": "It's named after the planet Neptune!",
    "use": "Used only for scientific research."
  },
  {
    "number": 94,
    "symbol": "Pu",
    "name": "Plutonium",
    "mass": "(244)",
    "category": "actinide",
    "period": 7,
    "group": 8,
    "phase": "solid",
    "discovered": "1940",
    "fact": "It's named after the dwarf planet Pluto!",
    "use": "Powers deep-space probes and satellites."
  },
  {
    "number": 95,
    "symbol": "Am",
    "name": "Americium",
    "mass": "(243)",
    "category": "actinide",
    "period": 7,
    "group": 9,
    "phase": "solid",
    "discovered": "1944",
    "fact": "There's a tiny bit inside many home smoke detectors!",
    "use": "Helps smoke detectors sense fire."
  },
  {
    "number": 96,
    "symbol": "Cm",
    "name": "Curium",
    "mass": "(247)",
    "category": "actinide",
    "period": 7,
    "group": 10,
    "phase": "solid",
    "discovered": "1944",
    "fact": "It's named after scientists Marie and Pierre Curie!",
    "use": "Used to power instruments on Mars rovers."
  },
  {
    "number": 97,
    "symbol": "Bk",
    "name": "Berkelium",
    "mass": "(247)",
    "category": "actinide",
    "period": 7,
    "group": 11,
    "phase": "solid",
    "discovered": "1949",
    "fact": "It's named after Berkeley, California, where it was made!",
    "use": "Used only in scientific laboratories."
  },
  {
    "number": 98,
    "symbol": "Cf",
    "name": "Californium",
    "mass": "(251)",
    "category": "actinide",
    "period": 7,
    "group": 12,
    "phase": "solid",
    "discovered": "1950",
    "fact": "It's one of the most expensive materials on Earth!",
    "use": "Helps find hidden metal and start nuclear reactors."
  },
  {
    "number": 99,
    "symbol": "Es",
    "name": "Einsteinium",
    "mass": "(252)",
    "category": "actinide",
    "period": 7,
    "group": 13,
    "phase": "solid",
    "discovered": "1952",
    "fact": "It's named after the famous scientist Albert Einstein!",
    "use": "Used only for scientific research."
  },
  {
    "number": 100,
    "symbol": "Fm",
    "name": "Fermium",
    "mass": "(257)",
    "category": "actinide",
    "period": 7,
    "group": 14,
    "phase": "solid",
    "discovered": "1952",
    "fact": "It's named after physicist Enrico Fermi!",
    "use": "Used only for scientific research."
  },
  {
    "number": 101,
    "symbol": "Md",
    "name": "Mendelevium",
    "mass": "(258)",
    "category": "actinide",
    "period": 7,
    "group": 15,
    "phase": "solid",
    "discovered": "1955",
    "fact": "It's named after Mendeleev, who invented the periodic table!",
    "use": "Used only for scientific research."
  },
  {
    "number": 102,
    "symbol": "No",
    "name": "Nobelium",
    "mass": "(259)",
    "category": "actinide",
    "period": 7,
    "group": 16,
    "phase": "solid",
    "discovered": "1958",
    "fact": "It's named after Alfred Nobel, who created the Nobel Prize!",
    "use": "Used only for scientific research."
  },
  {
    "number": 103,
    "symbol": "Lr",
    "name": "Lawrencium",
    "mass": "(266)",
    "category": "actinide",
    "period": 7,
    "group": 17,
    "phase": "solid",
    "discovered": "1961",
    "fact": "It's named after Ernest Lawrence, inventor of a famous particle accelerator!",
    "use": "Used only for scientific research."
  },
  {
    "number": 104,
    "symbol": "Rf",
    "name": "Rutherfordium",
    "mass": "(267)",
    "category": "transition-metal",
    "period": 7,
    "group": 4,
    "phase": "solid",
    "discovered": "1964",
    "fact": "It's named after physicist Ernest Rutherford!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 105,
    "symbol": "Db",
    "name": "Dubnium",
    "mass": "(268)",
    "category": "transition-metal",
    "period": 7,
    "group": 5,
    "phase": "solid",
    "discovered": "1968",
    "fact": "It's named after Dubna, a science city in Russia!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 106,
    "symbol": "Sg",
    "name": "Seaborgium",
    "mass": "(269)",
    "category": "transition-metal",
    "period": 7,
    "group": 6,
    "phase": "solid",
    "discovered": "1974",
    "fact": "It's named after scientist Glenn Seaborg, while he was still alive!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 107,
    "symbol": "Bh",
    "name": "Bohrium",
    "mass": "(270)",
    "category": "transition-metal",
    "period": 7,
    "group": 7,
    "phase": "solid",
    "discovered": "1981",
    "fact": "It's named after physicist Niels Bohr!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 108,
    "symbol": "Hs",
    "name": "Hassium",
    "mass": "(269)",
    "category": "transition-metal",
    "period": 7,
    "group": 8,
    "phase": "solid",
    "discovered": "1984",
    "fact": "It's named after Hesse, a state in Germany!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 109,
    "symbol": "Mt",
    "name": "Meitnerium",
    "mass": "(278)",
    "category": "transition-metal",
    "period": 7,
    "group": 9,
    "phase": "solid",
    "discovered": "1982",
    "fact": "It's named after scientist Lise Meitner!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 110,
    "symbol": "Ds",
    "name": "Darmstadtium",
    "mass": "(281)",
    "category": "transition-metal",
    "period": 7,
    "group": 10,
    "phase": "solid",
    "discovered": "1994",
    "fact": "It's named after Darmstadt, the German city where it was made!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 111,
    "symbol": "Rg",
    "name": "Roentgenium",
    "mass": "(282)",
    "category": "transition-metal",
    "period": 7,
    "group": 11,
    "phase": "solid",
    "discovered": "1994",
    "fact": "It's named after Wilhelm Rontgen, who discovered X-rays!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 112,
    "symbol": "Cn",
    "name": "Copernicium",
    "mass": "(285)",
    "category": "transition-metal",
    "period": 7,
    "group": 12,
    "phase": "solid",
    "discovered": "1996",
    "fact": "It's named after astronomer Nicolaus Copernicus!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 113,
    "symbol": "Nh",
    "name": "Nihonium",
    "mass": "(286)",
    "category": "post-transition-metal",
    "period": 7,
    "group": 13,
    "phase": "solid",
    "discovered": "2004",
    "fact": "It's named after Japan, where it was discovered ('Nihon')!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 114,
    "symbol": "Fl",
    "name": "Flerovium",
    "mass": "(289)",
    "category": "post-transition-metal",
    "period": 7,
    "group": 14,
    "phase": "solid",
    "discovered": "1998",
    "fact": "It's named after the Flerov Lab in Russia!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 115,
    "symbol": "Mc",
    "name": "Moscovium",
    "mass": "(290)",
    "category": "post-transition-metal",
    "period": 7,
    "group": 15,
    "phase": "solid",
    "discovered": "2003",
    "fact": "It's named after Moscow, where it was discovered!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 116,
    "symbol": "Lv",
    "name": "Livermorium",
    "mass": "(293)",
    "category": "post-transition-metal",
    "period": 7,
    "group": 16,
    "phase": "solid",
    "discovered": "2000",
    "fact": "It's named after Livermore, California!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 117,
    "symbol": "Ts",
    "name": "Tennessine",
    "mass": "(294)",
    "category": "halogen",
    "period": 7,
    "group": 17,
    "phase": "solid",
    "discovered": "2010",
    "fact": "It's named after the state of Tennessee!",
    "use": "Exists only briefly in physics labs."
  },
  {
    "number": 118,
    "symbol": "Og",
    "name": "Oganesson",
    "mass": "(294)",
    "category": "noble-gas",
    "period": 7,
    "group": 18,
    "phase": "solid",
    "discovered": "2002",
    "fact": "It's named after living scientist Yuri Oganessian!",
    "use": "Exists only briefly in physics labs."
  }
];

if (typeof module !== 'undefined') { module.exports = ELEMENTS; }
